### ISSUE TITLE
Some documentation please

### ISSUE THREAD

**Issue by ParkratPro** [salesagility/SuiteCRM-Outlook-Plugin#10]
While this might be a good solution -- there's nowhere to find out without installing it and doing trial and error -- and my error was that it wiped my outlook calendar clean. Now Outlook has disabled it altogether with no hint of what's going wrong. I understand I'm using the v2 beta, but the same comments apply for the plugin regardless. 

Please provide some installation/setup documentation, and end user documentation. Something akin to http://support.sugarcrm.com/Documentation/Plug-ins/MS_Outlook_Plug-in/MS_Outlook_Plug-in_User_Guide_2.x/.  How is this plugin expected to work? When syncing contacts, how can I control which contacts get synced. Can I push a single e-mail to a lead/contact/account, etc., or are all e-mails synced? All questions that could and should already be answered in a user doc. Thanks.

**Comment by lispeedyg** [comment]
I'm guessing there is no documentation.  I posted the same question in the Community Forum today.  I'm not certain how to use this plugin.  I seemed to have installed it and configured it in Outlook 2013.  However, noting is being sync'd.  Perhaps we can figure this out on our own??  Have you been able to use any of it's functions?  I'm guessing (for me) it might be a permissions issue.

**Comment by murdal** [comment]
We are just finalising the documentation which includes both setup and end user documentation. This will be available shortly.

**Comment by lispeedyg** [comment]
Thanks for this.  As a follow-on to this are there any video's that describe the functionality/usability of the entirety of SuiteCRM?  I'm not finding very much out there.  And, mostly only find SugarCRM..  Any direction would be appreciated.

**Comment by MJFellows** [comment]
How is the documentation progressing?

**Comment by CamoMacdonald** [comment]
Resolved in 3.0.0
Please look at https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin?tag=suitecrm 
This included the user guide
