### ISSUE TITLE
include LICENSE

### ISSUE THREAD

**Issue by Parikshit-Hooda** [salesagility/SuiteCRM-Outlook-Plugin#105]
#### Issue

We need License for this repo.

#### Expected Behavior

We should have a license document
#### Actual Behavior

No license present yet.
#### Possible Fix

Copy license from a similar repo
#### Steps to Reproduce

1.
2.
3.
4.

#### Context

high priority
#### Your Environment

* Outlook Plugin Version used:
* Outlook Client Version used:
* SuiteCRM Version used:
* Host (e.g. PC, Server):
* Operating System and version (e.g Windows 10):

**Comment by Parikshit-Hooda** [comment]
Happy to take this up as part of hacktoberfest!

**Comment by samus-aran** [comment]
Go for it. The Project's licence is LGPLv3

**Comment by sahilbhosale63** [comment]
Hi, Can I work on this?

**Comment by Parikshit-Hooda** [comment]
@sahilbhosale63 I am working on this.
HAHA thanks. I totally forgot about this!

**Comment by Parikshit-Hooda** [comment]
@samus-aran Please merge #107
