### ISSUE TITLE
UTC Dates and Time

### ISSUE THREAD

**Issue by andrewhegerty** [salesagility/SuiteCRM-Outlook-Plugin#11]
Hi,
I live in Australia's (+10hrs) time zone.  When I have the plugin syncing the calendar it moves all my meeting times to UTC.  This is quite an issue for me as my day calendar appears clear but my night calendar is full.

![error](https://cloud.githubusercontent.com/assets/18541309/14623233/a569c520-0613-11e6-924a-9a804812229f.png)

**Comment by Cerothen** [comment]
I can confirm the same is happening for me.

I enter a meeting in outlook at 2pm EST. It gets synced.

SuiteCRM shows the meeting as 2pm EST but then outlook gets updated and shows the meeting as 6pm EST.

**Comment by vmijalkovic** [comment]
Same here...

**Comment by rudnerbjoern** [comment]
I have the same Problem: User-Settings in CRM is GMT+2.
Meeting scheduled at 9:00 in CRM Show off as 7:00 in the Outlook Calendar.

**Comment by mayflowertech** [comment]
Same Guys... Chicago here.. Changes everything to + 5 hours

**Comment by raygrey** [comment]
I am based in Melbourne, Australia and the same problem is occurring for me. Will enter meeting into SuiteCRM at 12pm and it will sync it to Outlook 2016 at 2pm. Need to stop syncing until problem has been resolved.

**Comment by MJFellows** [comment]
Hi, I've got this problem too - is there a workaround?

**Comment by CamoMacdonald** [comment]
This should now be resolved in v3.0.0
