### ISSUE TITLE
Send and Archive Option

### ISSUE THREAD

**Issue by dgreeninger** [salesagility/SuiteCRM-Outlook-Plugin#12]
Hey guys! Great start on the plugin. :smile: 
Coming from the SugarCRM outlook archive plugin, I'm noticing one major button that's missing.
The 'Send and Archive'... 

Right now, I often respond to emails and want them to end up in the CRM, with my reply. In order to get the functionality, I have to send the email, then go into my sent folder and archive the mail. 

The SugarCRM plugin has a send and archive button that sends the email, and archives it into the CRM with one click. It's a nice little perk and probably not too hard to implement.

**Comment by dgreeninger** [comment]
I made a work around, that could be useful to someone else wanting to improve their user experience with the SuiteCRM plugin, as it currently functions.

- Create a new folder in your outlook mailbox called 'Archived Sent Mail'
- Go to the SuiteCRM Outlook plugin settings and select the 'Auto Archive' tab. 
- Select your new 'Archived Sent Mail' folder

Now the plugin will auto archive any mail that ends up in that folder.
I followed this guide: http://www.codetwo.com/kb/how-to-create-in-outlook-a-rule-moving-sent-mail-to-a-specified-folder/ and created a rule that moves a copy of the sent mail into my new Auto Archive folder, when I flag it with 'High Importance' and then click Send. 
The plugin, then gets the copy in the Auto Archive folder and archives it to SuiteCRM, as long as it doesn't have an attachment #1 

You can adjust your rule as you see fit.

**Comment by RossMNelson** [comment]
In the Settings of the Outlook Plugin under the Auto Archive tab there is a check box that states "Automatically Archive all inbound and Outbound mails" then below is a list of your Outlook folders.

In this list it is missing the Sent folder.

The work around is a great idea, however it would be much more user friendly to have the sent folder in the list to be able to mark the check box to automatically archive outbound emails.

**Comment by CamoMacdonald** [comment]
@dgreeninger @RossMNelson this has now been added to the most recent version of the plugin (3.0.2.2)

**Comment by RossMNelson** [comment]
@CamoMacdonald Thank you so much!!!
