### ISSUE TITLE
Calendar Sync brings in Calls not assigned to user

### ISSUE THREAD

**Issue by dgreeninger** [salesagility/SuiteCRM-Outlook-Plugin#13]
I used the calendar sync part of the plugin and it seems that it will bring in any Call that my user has permission to see. 
Since I'm a SuiteCRM Admin and can see everyone's call/meeting list this has created a large number of scheduled calls/meetings on my calendar, that I am not actually associated with. 

I'd suggest giving the user an option to only bring in Calls or Meetings they've created, by default.
Getting everything on an outlook calendar could be useful to a receptionist type role though, so maybe allowing them to select the option to pull everything, could still be useful. :smile:

**Comment by dhayner** [comment]
I also have seen this issue and made the error of mentioning it in the main SuiteCRM forums and not checking here.  Two users, two machines, same result: ALL calls/meetings pulled to Outlook.  I thought it could be depending on SecuritySuite Groups, so I made changes but no effect.  Not sure what the logic is behind this or why it behaves this way.

**Comment by RossMNelson** [comment]
I agree with this issue would make the calendar sync incredibly useful to the user.  We have over 40 users and each user has different preferences on how they would like to integrate their CRM calendar and Outlook calendar.  If would be very helpful to have the ability to filter what you items you would like to sync to your outlook calendar.

Filters

1.  Meetings
1.  Calls
1.  Tasks
1.  Assigned to
1.  Created by
1.  Security Groups
1.  Users
1.  All

**Comment by CamoMacdonald** [comment]
@dgreeninger @dhayner What version of SuiteCRM were you using?

**Comment by CamoMacdonald** [comment]
Resolved in v3.0.0
