### ISSUE TITLE
Cannot Enable Plugin on a terminal server

### ISSUE THREAD

**Issue by dazzler22** [salesagility/SuiteCRM-Outlook-Plugin#16]
(adding this here as cannot see it in the issues)

at the moment im unable to enable for regular users on a terminal server, only admins can enable the plugin.

**Comment by jack7anderson7** [comment]
Hi @dazzler22,
My suggestion would be to upgrade to the latest version of the SuiteCRM Addin (3.0.18) and let me know if this is still and issue
