### ISSUE TITLE
Bug with Archiving email to custom module

### ISSUE THREAD

**Issue by phanik18** [salesagility/SuiteCRM-Outlook-Plugin#17]
Hi,

When I manually archive an email in Outlook 2016 ( Office 365 )  to one of my custom modules plugin says it has been archived successfully. Although the entry in the database `emails` table; columns parent_type and parent_id are both NULL, and in SuiteCRM email is not displayed in "History " tab

**Comment by samus-aran** [comment]
This has been introduced in v3.0.3
