### ISSUE TITLE
Outlook plugin 2RC will not connect to SuiteCRM

### ISSUE THREAD

**Issue by MarkEdwardsFashionglass** [salesagility/SuiteCRM-Outlook-Plugin#18]
We have SuiteCRM 7.6.4 installed, and Outlook plugin 2RC installed.

When trying to test or save connection settings (http://server:8080/SuiteCRM), I get an error dialog:

Unexpected character encountered while parsing value: <.Path '', line 0, position 0.

I do not get this error when testing or saving on my localhost version, for whatever that's worth.

**Comment by CamoMacdonald** [comment]
Do you connect to you CRM instance at that URL? (http://server:8080/SuiteCRM)

**Comment by aeroflyte** [comment]
Did you fix this?  I get the same error.

**Comment by CamoMacdonald** [comment]
Resolved in v3.0.0
