### ISSUE TITLE
Install Package is not supported by this processor type

### ISSUE THREAD

**Issue by RiteTrack** [salesagility/SuiteCRM-Outlook-Plugin#19]
Attempting to install 2.0RC on Windows 7 and Windows XP 32 bit machines generates this error.  I suspect it is only supported on 64 bit.  Can anyone confirm this?

**Comment by dhayner** [comment]
The 2.0RC you speak of -- is that published by SalesAgility or SugarCRM?  I don't believe the SugarCRM version works properly with Suite.  Open to hearing otherwise!

**Comment by RiteTrack** [comment]
I'm referring to the SuiteCRM version.

**Comment by CamoMacdonald** [comment]
@RiteTrack Hi,
Were you having an issue installing SuiteCRM or could you please expand on the issue with the Outlook plugin you were having?

**Comment by CamoMacdonald** [comment]
@RiteTrack @dhayner With the new Outlook plugin v3.0.0 we no longer support 2007, however support 2010, 2013 and 2016.
https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin?tag=suitecrm
