### ISSUE TITLE
Search starting with a two digit number interpreted as Unicode character on server side

### ISSUE THREAD

**Issue by Szellszi** [salesagility/SuiteCRM-Outlook-Plugin#2]
Hey guys,

I have encountered an error while using the outlook plugin.
If you try to search for a linked entity when archiving, and the string is starts with a two digit number then the string is interpreted as a unicode charater on the server side, because of the starting '%' sign.

The result of this behaviour is that the server returns nothing as a result.

In my case it was 15, so the '%15%' interpreted as &#039;NAK%&#039; where NAK is the special Not Acknowledged symbol in Unicode. (https://en.wikipedia.org/wiki/Negative-acknowledge_character)

I tried to set the encoding in the HttpWebRequest, but then everything stopped working :)

**Comment by CamoMacdonald** [comment]
Resolved in 3.0.0
