### ISSUE TITLE
Could not finish installation on Win10 with Outlook 2007

### ISSUE THREAD

**Issue by harihasina** [salesagility/SuiteCRM-Outlook-Plugin#20]
I was attempting to install SuiteCRM Outlook Plugin on a Win10 VM for Outlook 2007.

Installation correctly finished when running setup.exe as administrator. But, experienced failure while deploying "file:///C:/Program Files (x86)/SuiteCRMAddIn/SuiteCRMAddIn.vsto".

It seems the following required image-files are missing from "C:/Program Files (x86)/SuiteCRMAddIn/Images" :
**\* createopp.png, CreateContact.png, CreateContact.jpg, CreateLead.png, CreateAccount.png, CreateAccount.jpg, CreateRecords.png, call.png, bug.png ***
After I added substitution image=files, deploiment went a little forward but again failed with the following message : 
Nom : SuiteCRMAddIn
De : file:///C:/Program Files (x86)/SuiteCRMAddIn/SuiteCRMAddIn.vsto

*************\* Texte de l'exception **************
System.Deployment.Application.InvalidDeploymentException: Le fichier createopp.png possède un hachage calculé différent de celui spécifié dans le manifeste.
   à Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.DownloadAddIn(TimeSpan timeout)
   à Microsoft.VisualStudio.Tools.Applications.Deployment.ClickOnceAddInDeploymentManager.InstallAddIn()

Can anyone help?

**Comment by CamoMacdonald** [comment]
@harihasina With the new Outlook plugin v3.0.0 we no longer support 2007, however support 2010, 2013 and 2016.
https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin?tag=suitecrm
