### ISSUE TITLE
Add-in inactive from start on Outlook 2013 64bit

### ISSUE THREAD

**Issue by TrueSelenis** [salesagility/SuiteCRM-Outlook-Plugin#21]
The Plugin is listed in Addin list after installation but as inactive
Outlook 2013 64bit German on Windows 7 Pro 64 bit
![outlookplugin_inactive](https://cloud.githubusercontent.com/assets/20065704/17555754/0894bbe0-5f11-11e6-8543-fca22c10f64b.PNG)

**Comment by gflauder** [comment]
Is it active in COM-Add-ins ? Click the go button next to COM-Add Ins and see if it's checked off and running.

**Comment by entwickler5** [comment]
Same here. AddIn not checked, and when checking it and restarting Outlook it remains the same.

Outlook 2010 14.0.7113.5000 SP1 MSO 14.0.7128.5000

**Comment by CamoMacdonald** [comment]
You can now download V3.0.0 at: https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin?tag=suitecrm
This includes a User Guide that may be able to resolve any issues you are having
