### ISSUE TITLE
SuiteCRM Outlook Plugin stopped working

### ISSUE THREAD

**Issue by aeroflyte** [salesagility/SuiteCRM-Outlook-Plugin#25]
I've tried everything that I can think of. The Outlook plugin was working ok. I experienced the time shift problem and the repeated prompt to save on exit. I did not realize that it was the plugin. Then, it stopped connecting to the CRM and I get the error that is in the attached picture.

I proceeded to uninstall the plugin from Outlook and from the PC to see if a fresh install would work. Same result.

Should I re-install SuiteCRM over top of what I have? I don't know what else to do other than buy one of the commercial Outlook connectors.

If I do that what is the best one?

I would be very grateful for help on this. I really need this to sync up with Outlook.

Thank you
John
I don't know how else to be notified if someone can help me, reply to this email.

john@compositeautomation.com

![suitecrm oulook plugin error](https://cloud.githubusercontent.com/assets/23349209/22622802/308efbc2-eb13-11e6-9cd7-20d0a973e359.jpg)

**Comment by CamoMacdonald** [comment]
Hi @aeroflyte,

We will be releasing a new version of the Outlook plugin soon, this should fix these issues

**Comment by CamoMacdonald** [comment]
Resolved in v3.0.0
