### ISSUE TITLE
How to install and configure Version 3.0 ?

### ISSUE THREAD

**Issue by sasha2002** [salesagility/SuiteCRM-Outlook-Plugin#27]
How is possible to get Community license?
#### Issue

I compiled it, installed, and it asking license and wont save.
#### Steps to Reproduce

1. Complie v3
2. Install it
3. Configure it
4. Try to save

#### Your Environment

* OutLook Client Version used:
* SuiteCRM Version used:
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by CamoMacdonald** [comment]
you can obtain the licence from https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin?tag=suitecrm

**Comment by sasha2002** [comment]
Community license?
As i see here is just Commercial

**Comment by samus-aran** [comment]
Hi @sasha2002 

The SuiteCRM Outlook Plugin v3.0.0 + is an open source LGPLv3 licensed plug-in.

You can acquire the code directly from the GitHub repository, compile it, modify it and use it at no charge. Though Github versions do not come with any support or warranties and may not always be the latest version.

You can also purchase a licensed and supported version of plugin that will work out-of-the-box from the SuiteCRM store. Purchased versions are fully supported by the project and regular updates will be available to licensed users.

You can purchase licenses here: https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin?tag=suitecrm

You can view the User Guides for installation here: https://store.suitecrm.com/docs/SuiteCRM-official-outlook-plugin

The revenues from the license purchase are used to maintain, extend and improve both the Outlook plugin and core SuiteCRM.

**Comment by sasha2002** [comment]
@samus-aran What i do:
Grab code, compile it install compiled exe.
What i'm doing wrong?

**Comment by pgorod** [comment]
@sasha2002 you probably need to change the code to remove the license check. Possible, though not very respectful of the option that SalesAgility made to license the code. 

I wouldn't do that if I was using the plugin commercially, though - we all like freebies but they have given so much to this community, for free, that I think they deserve some room to try different models to monetize their investments, like they're trying here. I can understand why they chose this for the Outlook plugin, they're not a Windows company, they don't normally do Windows developments, so it's an extra effort for them.

**Comment by sasha2002** [comment]
I understood, but if you put code here, please be honest and write onto the code one license that is for community.
I don't think that this is not respectful.

**Comment by samus-aran** [comment]
@sasha2002  We have been perfectly honest in this regards.  The code is completely free to use, but it requires a developer to modify it and use it without a license.  There is no community license but rather the code itself is the community license.

Its a small inconvenience to yourself it seems to have a fully fledged piece of software that doesn't work OTB because you wish to not purchase a license. :)

**Comment by jyotiraghav93** [comment]
Can you please explain the steps of how to compile this suitecrm & outlook integration plugin?
