### ISSUE TITLE
Turn Auto-Archive OFF by default

### ISSUE THREAD

**Issue by EZS-JD** [salesagility/SuiteCRM-Outlook-Plugin#3]
I vote for changing the default behavior of the plugin to NOT auto-archive all mails going in and out of Outlook!

I'd like to offer the plugin to our employees to install as they please, but the fact that they have to think of desabling the auto-archiving means that, for certain, some will forget this at some point after freshly installing the plugin (or updating it in the future)...
Would give me better sleep if this was off by default!

Thanks for considering this!

**Comment by EZS-JD** [comment]
In the meantime: Is there any way I can change the installer myself, as to deselect this checkbox by default?
Or could you supply me with a different version of the installer where this checkbox is deselected by default?

**Comment by CamoMacdonald** [comment]
Auto Archiving should be off on install for v3

**Comment by simon-brooke** [comment]
Uhmm... @CamoMacdonald, AutoArchive is still True by default in both clsSettings (v3.0.0.6) and Settings.settins (v3.0.0.7). Should it be False by default?

**Comment by CamoMacdonald** [comment]
@EZS-JD  this has now been added to the most recent version of the plugin (3.0.2.2)
