### ISSUE TITLE
Search Not working effectively

### ISSUE THREAD

**Issue by etsitsupport** [salesagility/SuiteCRM-Outlook-Plugin#32]
I installed SuiteCRM outlook plugin V2.0... While searching for records certain times its searching fine. Certain times its not though the record is existing. 

#### Issue
I searched for 53 Loyang in the search box.. 53 Loyang Drive, 4 storey FACTORY is the opportunity name is the crm . But the opportunity did not show up in the search result panel. Then I searched using "53 Loyang Drive, 4 storey FACTORY" the opportunity showed up. The search requires improvement. 

#### Expected Behavior
searching based on part words like 53 Loyang should show the opportunity "53 Loyang Drive, 4 storey FACTORY"

#### Actual Behavior
53 Loyang Drive, 4 storey FACTORY is not being displayed in the result panel.

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* Outlook Plugin Version used: SuiteCRM outlook plugin V2.0
* Outlook Client Version used: Outlook 2013
* SuiteCRM Version used: 
* Host (e.g. PC, Server):
* Operating System and version (e.g Windows 10): Windows 10

**Comment by CamoMacdonald** [comment]
This is no longer an issue with the most recent version of the plugin

**Comment by etsitsupport** [comment]
Hi ,
        Which is the most recent version of the plugin. ?

**Comment by CamoMacdonald** [comment]
@etsitsupport 3.0.1
