### ISSUE TITLE
Attendee with plugin becomes organiser on external appointments

### ISSUE THREAD

**Issue by virtualme123** [salesagility/SuiteCRM-Outlook-Plugin#33]
#### Issue

A user had an Outlook appointment come through but for some reason he couldn't accept the appointment. Some how the permissions seemed to have changed so he was the organiser and therefore Outlook didn't think he needed to accept it. I am assuming that during a sync to the CRM the pluggin perhaps changed the permission. Interestingly his Outlook app on his phone still allowed him to accept the appointment which would make sense if the plugin within Outlook had caused the issue.

#### Expected Behavior

When you are invited into an appointment you should be able to accept, decline etc. The appointment should sync to the CRM against the organisers contact record (if exists).

#### Actual Behavior

Appointment received and organiser overwritten to the attendee (plugin owner) and can't accept appointment.

#### Steps to Reproduce

Difficult to replicate, but hoping this might be something others have encountered?

#### Context

Unfortunately we've had to turn off the automatic calendar syncing which otherwise worked really quite well.

#### Your Environment

* Outlook Plugin Version used: 3.0.1.0
* Outlook Client Version used: Outlook 2013 
* SuiteCRM Version used: 7.8.1
* Host (e.g. PC, Server):  Ubuntu 14.04, MySQL 5.6, PHP 5.9
* Operating System and version (e.g Windows 10): Windows 10

**Comment by simon-brooke** [comment]
Thanks for the report; it isn't one I've seen, but I can well believe it's real. I'll investigate.

**Comment by jack7anderson7** [comment]
Hi,
My suggestion would be to upgrade to the latest version of the SuiteCRM Addin (3.0.18) and let me know if this is still and issue
