### ISSUE TITLE
this is not opening in visualstudio 2015 community edition . it shows project unavailabe

### ISSUE THREAD

**Issue by dineshgola025** [salesagility/SuiteCRM-Outlook-Plugin#34]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* Outlook Plugin Version used:
* Outlook Client Version used:
* SuiteCRM Version used:
* Host (e.g. PC, Server):
* Operating System and version (e.g Windows 10):

**Comment by simon-brooke** [comment]
That will be the setup project (SuiteCRMAddInSetup), which requires that you have InstallShield installed. I'm sorry, there's nothing I know of you can do about that, apart from paying $$$ either to the InstallShield people, or to MicroSoft for a full VisualStudio licence. I don't know of an open source Windows installer which will do what we need.
