### ISSUE TITLE
i need this plugin setup.exe if anyone can provide.

### ISSUE THREAD

**Issue by dineshgola025** [salesagility/SuiteCRM-Outlook-Plugin#35]
#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* Outlook Plugin Version used:
* Outlook Client Version used:
* SuiteCRM Version used:
* Host (e.g. PC, Server):
* Operating System and version (e.g Windows 10):

**Comment by CamoMacdonald** [comment]
Hi @dineshgola025 

The SuiteCRM Outlook Plugin v3.0.0 + is an open source LGPLv3 licensed plug-in.

You can acquire the code directly from the GitHub repository, compile it, modify it and use it at no charge. Though Github versions do not come with any support or warranties and may not always be the latest version.

You can also purchase a licensed and supported version of plugin that will work out-of-the-box from the SuiteCRM store(this includes the setup.exe). Purchased versions are fully supported by the project and regular updates will be available to licensed users. 

You can purchase licenses here: https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin?tag=suitecrm

You can view the User Guides for installation here: https://store.suitecrm.com/docs/SuiteCRM-official-outlook-plugin

The revenue from the license purchases are used to maintain, extend and improve both the Outlook plugin and core SuiteCRM.
