### ISSUE TITLE
SuiteCRM Outlook Plug-in for Mac?

### ISSUE THREAD

**Issue by eigernf** [salesagility/SuiteCRM-Outlook-Plugin#39]
#### Are you working on an outlook plugin for Mac?  If yes, when do you think it will be available?  If no.  Boooo!
Thanks,

#### Steps to Reproduce

1.
2.
3.
4.

#### Your Environment

* Outlook Plugin Version used:
* Outlook Client Version used:
* SuiteCRM Version used:
* Host (e.g. PC, Server):
* Operating System and version (e.g Windows 10): Mac

**Comment by samus-aran** [comment]
Hi @eigernf ,

There is nothing on the roadmap for Mac unfortunately.
