### ISSUE TITLE
upgraded to 3.0.3 -> ldap issue- PLUG IN NO LONGER OPERATIONAL 

### ISSUE THREAD

**Issue by bmwtourer** [salesagility/SuiteCRM-Outlook-Plugin#45]
Was using previous version (recently)
uninstalled and installed 3.0.3 with great expectations...

from the plugin I can not login with my regular ldap login (which I use on SuiteCRM), it was working with previous version.

If I use another NON ldap login /user name then I can connect...

This is very urgent to get fixed because the plugin is ***completely useless***

**Comment by samus-aran** [comment]
@bmwtourer This has been resolved the latest release v3.0.4
