### ISSUE TITLE
Outlook Plugin 3.0.3.0 License Key Request

### ISSUE THREAD

**Issue by themotherconfessor** [salesagility/SuiteCRM-Outlook-Plugin#47]
Hello,

I have successfully installed and connected the plugin to my SuiteCRM installation and the test works.

However, it wont let me use anything to do with the plugin as it asks for a license key. On the SuiteCRM store it says that it's free to download and compile the code yourself, but I can't find a license key anywhere in the files or documentation.

I don't know if I'm just being an idiot and overlooking it somehow, but I can't even test the plugin without the license key.

#### Issue
Open source but asks for license key.

#### Expected Behaviour
It doesn't ask for a license key as it's open source.

#### Actual Behaviour
It asks for a license key.

#### Steps to Reproduce
1. Download github files
2. Install files
3. Setup SuiteCRM server information
4. Try to archive email/use plugin

#### Context
It has effected me by preventing me from testing out the plugin.

#### Your Environment
Windows 10 genuine and licensed up to date
Outlook 2016 genuine and licensed up to date

* Outlook Plugin Version used: 3.0.3.0
* Outlook Client Version used: 1703 Build 7967.2161
* SuiteCRM Version used: Beta 7.9.0
* Host (e.g. PC, Server): Server - FastComet 
* Operating System and version (e.g Windows 10): Windows 10 Version 10.0.15063 Build 15063

Any help would be appreciated.

Many thanks.

**Comment by simon-brooke** [comment]
It is open source. You are completely entitled to download the source from this site, make the single small alteration that disables the licence key check, compile it and run it. There's absolutely nothing hidden or underhand about this.

Won't fix.
