### ISSUE TITLE
Sync issues with email and calendar

### ISSUE THREAD

**Issue by johndiff** [salesagility/SuiteCRM-Outlook-Plugin#48]
#### Issue
ERROR | EmailArchiving.ProcessFolderItems; folder Calendar:
System.Runtime.InteropServices.COMException (0x80020009): The property "ReceivedTime" is unknown.
   at Microsoft.Office.Interop.Outlook._Items.Restrict(String Filter)
   at SuiteCRMAddIn.BusinessLogic.EmailArchiving.ArchiveFolderItems(Folder objFolder, DateTime minReceivedDateTime)
Data:System.Collections.ListDictionaryInternal
HResult:-2147352567
#### Expected Behavior
All items should be syncing to outlook

#### Actual Behavior
Calendar Items are missing - Looks like the recurring calendar items all missing.  None of my inbox is archiving to Suitecrm even though they are flagged in outlook

#### Steps to Reproduce

1.
2.
3.
4.

#### Context
I am trying to have it so both Suitecrm and Outlook have the same info when it comes toCalendar Contacts and Email

#### Your Environment

* Outlook Plugin Version used:3.0.4
* Outlook Client Version used:2016
* SuiteCRM Version used:7.8.3
* Host (e.g. PC, Server): Server
* Operating System and version (e.g Windows 10): Workstation Windows 10 Server: Windows 2012 R2

**Comment by samus-aran** [comment]
Hi John, I believe we are assisting you in the store cases system.  I will mark this as a duplicate and the technical support will assist you on the store.
