### ISSUE TITLE
Server (500) Interal Server Error

### ISSUE THREAD

**Issue by AmyWalters123** [salesagility/SuiteCRM-Outlook-Plugin#51]
#### Issue
When I manually try to sync the error comes up saying - 

An error was encountered while querying module 'accounts'. The erroe('The remote server returned an error: (500) Internal Server Error.') has been logged

#### Expected Behavior
That it syncs with Suite CRM

#### Actual Behavior
It crashes outlook and I have to Ctrl-Alt-Delete > task manager > end application

#### Steps to Reproduce
1. Right click on email from someone I know is in the CRM
2. Click Manually archive button
3. Searh
4. Error message keeps popping up

#### Context
Unable to use the plugin and investigate free trial
High, if I can't use it I may not want to purchase it.

#### Your Environment

* Outlook Plugin Version used: 3.0.5.0
* Outlook Client Version used: 2016
* SuiteCRM Version used: 7.9.2
* Host (e.g. PC, Server): Server
* Operating System and version (e.g Windows 10): Windows 10 Pro

**Comment by simon-brooke** [comment]
Hi Amy

Thanks for your report. Can you, in the settings dialog, set the logging level to 'Debug' (on the 'Information' tab), use the plugin until you get the problem again, then immediately open the log directory (there's a link on the 'Information' tab of the settings dialog) and copy the log (suitecrmoutlook.log) to another directory?

With logging set to Debug, there will be confidential information in the log, including the email addresses of your contacts and the subjects of your emails; however, there will also be full dumps of the exception(s) that are causing your problem and from those you may be able to diagnose the problem yourself.

If you can't, please open a thread for the issue [here](https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin), and someone from SalesAgility will get in touch with you. They will probably ask for a copy of the log - check it to make sure that there isn't anything in it you wouldn't want going outside your organisation before sending it.

**Comment by AmyWalters123** [comment]
Hello Simon,

Thanks for your help I have done everything but I’m not sure how to save it to another directory.

Could you talk me through how to do that?

Thank you,

Amy

**Comment by jack7anderson7** [comment]
Hi,
My suggestion would be to upgrade to the latest version of the SuiteCRM Addin (3.0.18) and let me know if this is still and issue
