### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by robertantonyjaikumar** [salesagility/SuiteCRM-Outlook-Plugin#59]
I just downloaded and run the file in Visual Studio 2015 
I removed the solution 
SuiteCRMAddInSetup\SuiteCRMAddInSetup.isproj
And I built the solution. But it throws some error 

The command "doxygen.exe ..\Doxyfile" exited with code 9009.	
C:\wamp\www\plugin\SuiteCRM-Outlook-Plugin-master\SuiteCRMAddIn\SuiteCRMAddIn.csproj	
line : 514

I got above error. can anyone help to solve this?

**Comment by simon-brooke** [comment]
Hi

I use [Doxygen](http://www.stack.nl/~dimitri/doxygen/) to generate documentation for the project; you'll need to install it, or to remove the dependency from the build file.

This isn't critical, of course - the project will build if you just remove the dependency. But the documentation is useful!

**Comment by jaikumarpd** [comment]
Thanks simon :) Let me try this.

**Comment by Rahuljain1947** [comment]
Hi Simon, 
I'm a newbie and would greatly appreciate if you could pls advise where can I remove the doxygen dependency from, which file/files. I'm getting the same error and hence not able to build the solution.
Thanks.

**Comment by simon-brooke** [comment]
Quick answer, download and install Doxygen. It's open source and free, works with many languages, and will encourage you to write better documentation. 

Forthe precise answer you want, wait until I get into the office tomorrow.
