### ISSUE TITLE
Unable to use modern SSL configuration (needs TLSv1.0) 

### ISSUE THREAD

**Issue by LEAP-nishit** [salesagility/SuiteCRM-Outlook-Plugin#60]
Plugin does not work for sites using a modern Cipher protocol. 

#### Issue
When using a modern ssl configuration ([for example as recommended my Mozilla](https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.18&openssl=1.0.1e&hsts=yes&profile=modern)) the Addin fails to login. 

The addin appears to work when enabline TLSv1.0 as an allowed SSLProtocol. 

#### Expected Behavior
The addin should be usable using modern secure SSL configuration and not forced to use TLSv1.0. 

#### Actual Behavior
The addin fails to login and renders it unusable. 

#### Possible Fix
No fix know. Current workaround is to enable TLSv1.0 . 

#### Steps to Reproduce
1. Use SSL configuration recommended [by Mozilla](https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.18&openssl=1.0.1e&hsts=yes&profile=modern)
2. Install Addin and attempt to login

#### Context
We just purchased 10 licenses as an initial deployment and found we needed to downgrade our SSL configurations to be able to use it. 

#### Your Environment
* Outlook Plugin Version used:  3.0.9.0
* Outlook Client Version used: Outlook 2016 Version 1705 
* SuiteCRM Version used: 7.8.8
* Host (e.g. PC, Server): Server
* Operating System and version (e.g Windows 10): Windows 10

**Comment by berthelemy** [comment]
We're having a similar problem. We can't login, and our server is using TLSv1.2 and TLSv1.3.

It'd be good to know if this really is an issue with the plugin not.

**Comment by cameronblaikie** [comment]
Hi there,
Previously the library used should've have defaulted to TLS 1.2 where available however that didn't appear to be the case. With v3.0.18 we have upgraded to .NET 4.6 which by default sets TLS library to be used at 1.2.
Please re-open if you are still having issues with this protocol.
