### ISSUE TITLE
Problems in DirectAccess/Citrix environment 

### ISSUE THREAD

**Issue by andrerav** [salesagility/SuiteCRM-Outlook-Plugin#62]
Hi,

We are trying to use this plugin in a DirectAccess/Citrix environment, but we are having some problems getting the plugin to work. On a regular Windows 10 computer it works fine, and syncs both ways without any hickups. However, in the DirectAccess environment the plugin only seems to be able to log in to the SuiteCRM system, and then somehow stalls or hangs without logging any exceptions (or anything else for that matter if we increase the log level to Debug). It just goes silent and does nothing.

Are there anyone else who has any experience running this plugin in a DirectAccess or Citrix environment, and have experience any similar issues?

**Comment by simon-brooke** [comment]
Hi

We've had another user report of this issue, our reference bug #40. However, we haven't been able to reproduce it and at this moment it doesn't have high priority. If you post a report [here](https://store.suitecrm.com/support/SuiteCRM-official-outlook-plugin) it will get pushed up the priority stack.

Cheers

Simon

**Comment by andrerav** [comment]
Hi Simon,

I took a look at https://github.com/salesagility/SuiteCRM-Outlook-Plugin/pull/40 but I can't seem to find a description of the bug itself (referred to as #126, but I can't find that here nor at https://store.suitecrm.com/support/SuiteCRM-official-outlook-plugin). Do you have any more details on this bug?

Thanks,
Andreas

**Comment by simon-brooke** [comment]
Sorry, no, #40 is an internal bug reference. It's not public.

**Comment by andrerav** [comment]
Thanks for the info @simon-brooke, are there any general details you can share about this issue to help me assert whether or not we may be experiencing the same problem? Or are you confident that DirectAccess or/and Citrix is the likely culprit?

**Comment by andrerav** [comment]
Hi @simon-brooke, it seems we have been chasing a red herring here. The problem turned out to be a access control configuration combined with confusion between various environments with import/export access discrepancies between them. I apologize for the trouble. I will however open a small discussion on a logging tweak that could have been very helpful in this matter :)

**Comment by simon-brooke** [comment]
OK, thanks. I'll look forward to your logging suggestion.
