### ISSUE TITLE
LIKE % fix suggestion

### ISSUE THREAD

**Issue by AceWT** [salesagility/SuiteCRM-Outlook-Plugin#63]
#### Issue
Sometimes search does not yields results when entering search string

#### Expected Behavior
Should return results, eg contact searched by name.

#### Actual Behavior
No results displayed

#### Fix
ArchiveDialog.cs function ConstructQueryTextForModuleName
replace all "%" characters with "%25"
example:
`queryText = $"(cases.name LIKE '%{escapedSearchText}%' OR cases.case_number LIKE '{escapedSearchText}')";`
to
`queryText = $"(cases.name LIKE '%25{escapedSearchText}%25' OR cases.case_number LIKE '{escapedSearchText}')";`

#### Steps to Reproduce
1. Start archiving some mail
2. Enter search query: ceblablalba

#### Context
In above example query sent is .... LIKE '%ceblablalba%' .... and it is replaced to
LIKE 'Îblablalba%' -> see this link http://www.degraeve.com/reference/urlencoding.php

To avoid matching %ce to Î we should add %25ce which will then be decoded to %ce correctly.

* Outlook Plugin Version used: 3.x

**Comment by jack7anderson7** [comment]
Hi @AceWT,
My suggestion would be to upgrade to the latest version of the SuiteCRM Addin (3.0.18) and if you find that this is still an issue let me know and I'll reopen this issue
