### ISSUE TITLE
Discussion: Log level for log messages "{crmType} not added to CRM because X is not Y"

### ISSUE THREAD

**Issue by andrerav** [salesagility/SuiteCRM-Outlook-Plugin#64]
Hi,

We recently encountered a problem where a single misconfigured SuiteCRM instance caused a lot of confusion due to import access was not granted to a module combined with a plugin configured to allow outbound synchronisation. 

Currently this situation is logged here: https://github.com/salesagility/SuiteCRM-Outlook-Plugin/blob/master/SuiteCRMAddIn/BusinessLogic/Synchroniser.cs#L380

However, the log level is set to Info, which means that unless the user enables Info or Debug log levels in the plugin, this will slip under the radar and possibly cause unecessary confusion and bug hunting (like it did for us). 

I'd like to vet the idea that 1) this situation (as well as two other similar situations on lines 374 and 386) should be logged with Warning log level, and 2) also set the default log level on the plugin to Warning instead of Error and 3) if necessary do a cleanup of overzealous Warning logging that may currently exist in the plugin.

I'd be happy to supply a pull request for this, but I would like to hear your thoughts on this matter first. 

Thanks for your continued great work!

-Andreas

**Comment by jack7anderson7** [comment]
Hi @andrerav,
my suggestion would be to upgrade to the latest version of the SuiteCRM Addin (3.0.18) and from there let me know if this is still an issue for you.
