### ISSUE TITLE
To-From-Cc-Bcc fields are being blank

### ISSUE THREAD

**Issue by jay-greenassessors** [salesagility/SuiteCRM-Outlook-Plugin#67]
#### Issue
While archiving the emails, the Plugin pulls Subject and Body from Outlook to CRM but fails to pulls To-From-Cc-Bcc.

#### Expected Behavior
The plugin should pull To-From-Cc-Bcc fields too.

#### Actual Behavior
The Plugin pulls Subject and Body fields only

#### Possible Fix
Broken link?

#### Your Environment
* Outlook Plugin Version used: 3.0.9
* Outlook Client Version used: 2016 MSO (16.0.8730.2046) 32-bit
* SuiteCRM Version used: 7.9.5
* Host (e.g. PC, Server): Hosting Solution One - SuiteCRM:OnDemand
* Operating System and version (e.g Windows 10): Windows 8.1
![image](https://user-images.githubusercontent.com/34917918/34419773-b722ad14-ebfd-11e7-819c-2845f6240e13.png)

**Comment by simon-brooke** [comment]
Hi, please could you upgrade to 3.0.12 and verify whether you still have the problem?

Thanks.

**Comment by jay-greenassessors** [comment]
Thanks Simon!

How do I upgrade to 3.0.12? the below link gives 3.0.9:
https://store.suitecrm.com/addons/SuiteCRM-official-outlook-plugin

**Comment by jay-greenassessors** [comment]
Can someone please advise a solution to this issue?

The current release of the Outlook plugin is v3.0.9. Version 3.0.12 is the current state of the development branch and is not yet production ready.
https://store.suitecrm.com/support/SuiteCRM-official-outlook-plugin/847

Thanks.

**Comment by cameronblaikie** [comment]
Hi this should be resolved on both upgraded SuiteCRM and Outlook version. Please re-open is still an issue.
