### ISSUE TITLE
Deletion of calendar records

### ISSUE THREAD

**Issue by adderchog** [salesagility/SuiteCRM-Outlook-Plugin#68]
#### Issue
Twice now, all my calendar appointments (except for one or two) have vanished and have been placed in the deleted items folder. i have to select them all and move them back to the calendar. We're using O365 so not sure if this has anything to do with.

#### Expected Behavior
It shouldn't happen!

#### Context
it happens randomly.

#### Logs

[suitecrmoutlook.log](https://github.com/salesagility/SuiteCRM-Outlook-Plugin/files/1626177/suitecrmoutlook.log)

[suitecrmoutlook.log1.txt](https://github.com/salesagility/SuiteCRM-Outlook-Plugin/files/1626194/suitecrmoutlook.log1.txt)
[suitecrmoutlook.log2.txt](https://github.com/salesagility/SuiteCRM-Outlook-Plugin/files/1626196/suitecrmoutlook.log2.txt)
[suitecrmoutlook.log3.txt](https://github.com/salesagility/SuiteCRM-Outlook-Plugin/files/1626198/suitecrmoutlook.log3.txt)

#### Your Environment

* SuiteCRM Outlook Add-In v3.0.7.0 in Outlook version 16.0.0.4498
* SuiteCRM Version used: Version 7.4.3 Sugar Version 6.5.20 (Build 1001)
* Host (e.g. PC, Server): Windows
* Operating System and version Windows 10

**Comment by jack7anderson7** [comment]
We suggest you upgrade to the latest version of the SuiteCRM Addin (3.0.18) and if this is still an issue reopen this issue and let me know
