### ISSUE TITLE
Prompted to save on exit

### ISSUE THREAD

**Issue by digitalmcgrath** [salesagility/SuiteCRM-Outlook-Plugin#7]
I am using Outlook 2010 on Windows 7 and with the add-on installed, every time I exit, I am prompted to save at least 3 or 4 times.

**Comment by dazzler22** [comment]
I have this same issue, outlook 2013 running on windows 10 pro 64bit, recieveing 20+ do you wish to save...

**Comment by vmijalkovic** [comment]
Same here. Being asked twice every time I try to exit Outlook

**Comment by CamoMacdonald** [comment]
@digitalmcgrath @dazzler22  Can you please confirm if this is happening every time you close Outlook? or only under certain circumstances?
