### ISSUE TITLE
SuiteCRM button group missing with Outlook 2016

### ISSUE THREAD

**Issue by BitSprocket** [salesagility/SuiteCRM-Outlook-Plugin#70]
#### Issue
After installing and successfully connecting to SuiteCRM the button group that includes the Address Book button does not appear on any ribbon.  The SuiteCRM ribbon was added but it only contains the Archive and Settings button

#### Expected Behavior
Button for CRM Address book should be on a ribbon

#### Actual Behavior
Button group missing

#### Possible Fix
Unknown.  It would be helpful to update the docs to include a screenshot of Outlook2016

#### Steps to Reproduce
1. Download and install Outlook Addin
2. Restart Outlook
3. Configure credentials etc.
4. Find that the Addin did not add the Button Group and it's not available in Customize Ribbons either

#### Context
I do not have access to the SuiteCRM address book inside outlook.  I am also unable to create new contacts from new email that should appear in CRM.

#### Logs
-----------------------------
SuiteCRM Outlook Add-In v3.0.9.0 in Outlook version 16.0.0.8827
Auto-archiving: off
Logging level: Error
-----------------------------
2018-01-22 10:55:09,339 | Background | ERROR | Failed to connect to licence server because ProtocolError
System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at SuiteCRMAddIn.BusinessLogic.LicenceValidationHelper.Validate()
Data:System.Collections.ListDictionaryInternal
HResult:-2146233079
2018-01-22 10:55:09,359 | Background | ERROR | Licence server responded "Key is required."
2018-01-22 10:58:02,092 | VSTA_Main | ERROR | Auto-archiving: ON
2018-01-22 10:58:02,092 | VSTA_Main | ERROR | Logging level: Error
2018-01-22 10:58:27,410 | VSTA_Main | ERROR | Auto-archiving: ON
2018-01-22 10:58:27,410 | VSTA_Main | ERROR | Logging level: Error

#### Your Environment
* Outlook Plugin Version used: 3.0.9.0
* Outlook Client Version used:2016 Vn 1712 Build 8827.2148
* SuiteCRM Version used:7.9.9
* Host (e.g. PC, Server):Server
* Operating System and version (e.g Windows 10):Windows 10 Education Build 17074.rs_prerelease_flt.180116-1539

**Comment by cameronblaikie** [comment]
Hi there we haven't been able to reproduce this please upgrade to 3.0.18 and if possible if still an issue then re-open and provide a screenshot.
