### ISSUE TITLE
v3.0.11 can't compile on VS2015

### ISSUE THREAD

**Issue by sasha2002** [salesagility/SuiteCRM-Outlook-Plugin#72]
#### Issue

Can't make it work on VS2015.

Installed VSTO 2010, VSTO2015....

Can someone help, how to compile it successful?
#### Actual Behavior

SuiteCRM-Outlook-Plugin-3.0.11\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018: The "BumpVersion" task failed unexpectedly.
SuiteCRM-Outlook-Plugin-3.0.11\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018: System.IO.IOException: The process cannot access the file
\SuiteCRM-Outlook-Plugin-3.0.11\SuiteCRMAddinSetup\SuiteCRMAddinSetup.isl' because it is being used by another process.
#### Steps to Reproduce

1.
2.
3.
4.

#### Logs

------ Rebuild All started: Project: SuiteCRMAddIn, Configuration: Release Any CPU ------
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018: The "BumpVersion" task failed unexpectedly.
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018: System.IO.IOException: The process cannot access the file 'C:\SuiteCRM\SuiteCRMAddinSetup\SuiteCRMAddinSetup.isl' because it is being used by another process.
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at System.IO.File.WriteAllText(String path, String contents)
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at InlineCode.BumpVersion.Execute() in c:\Users\RuBoard\AppData\Local\Temp\2afqpqmz.0.cs:line 105
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\SuiteCRM\SuiteCRMAddIn\SuiteCRMAddIn.csproj(538,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
#### Your Environment

* Outlook Plugin Version used:
* Outlook Client Version used:
* SuiteCRM Version used:
* Host (e.g. PC, Server):
* Operating System and version (e.g Windows 10):

**Comment by sasha2002** [comment]
Found a way to compile :
1. Extract archive
2. Open SuiteCRMAddInSetup in installshield
3. Confirm that you want to upgrade
4. Close installshield
5. Open sln in VS2015
6. fix http://joxi.ru/823v4OSJL9l3mO
7. Compile

But right now i have another error :
http://joxi.ru/nAyJQzsY0gMwrZ

**Comment by simon-brooke** [comment]
Right, so the reason the BumpVersion task is failing is because you have the installer configuration file `SuiteCRMAddinSetup.isl` open in something else (possibly even in VisualStudio). Close that file.

If you're still having trouble you can remove BumpVersion from `[SuiteCrmAddin.csproj](https://github.com/salesagility/SuiteCRM-Outlook-Plugin/blob/master/SuiteCRMAddIn/SuiteCRMAddIn.csproj#L497)`.

BumpVersion isn't magic and it isn't strictly necessary, it just means I can clearly identify each build.

**Comment by mr2017x** [comment]
Ok i did it now somehow but still i need to put in serial, i thought this wouldn't be in os Version? How can i disable this?

**Comment by cameronblaikie** [comment]
Hi @mr2017x
If you are meaning serial = license then yes you would need to have a license even for the OS version (both versions are OS btw). You can understand and respect that we are not required to pinpoint exactly where to disable the license key check but you are free to explore the code in order to achieve this.
Thanks.
