### ISSUE TITLE
Error (407) Proxy Authentication Required

### ISSUE THREAD

**Issue by Rahuljain1947** [salesagility/SuiteCRM-Outlook-Plugin#8]
Hi All, 

When trying to test the connection, I am receiving the error 407 Proxy Authentication Required. We have already added our CRM as a trusted site and setup direct route to access the urls bypassing the proxy authentication but suspect will need to configure the firewall too. Our network engineer would like to know if there is a specific **port** that we need to open in our firewall for the Outlook plugin to connect successfully or any other config that is needed? Your response and help will be greatly appreciated. 

Thanks,
Rahul

**Comment by simon-brooke** [comment]
You almost certainly also need to add the licence validation server at https://store.suitecrm.com/.
