### ISSUE TITLE
license error in outlook

### ISSUE THREAD

**Issue by pblancka** [salesagility/SuiteCRM-Outlook-Plugin#84]
#### Issue

license error in outlook plugin

#### Expected Behavior

license is valid so should be accepted

#### Actual Behavior

license error in outlook plugin

#### Steps to Reproduce

1.
2.
3.
4.

#### Context

unusable, please help
[Log-09-11-2018.txt](https://github.com/salesagility/SuiteCRM-Outlook-Plugin/files/2472937/Log-09-11-2018.txt)
[suitecrmoutlook.log](https://github.com/salesagility/SuiteCRM-Outlook-Plugin/files/2472938/suitecrmoutlook.log)

#### Your Environment

* Outlook Plugin Version used:
* Outlook Client Version used:
* SuiteCRM Version used:
* Host (e.g. PC, Server):
* Operating System and version (e.g Windows 10):

**Comment by cameronblaikie** [comment]
Hi there,

License specific questions are best asked on the store. 

However we can see that the license check appears to be fine but the login to the CRM is failing.

2018-10-12 14:02:56,064 | Background | INFO  | User chose to disable add-in after licence check succeeded but login to CRM failed.
