### ISSUE TITLE
Manifest.php file Missing 

### ISSUE THREAD

**Issue by Narola123** [salesagility/SuiteCRM-Outlook-Plugin#9]
No manifest.php file found in SuiteCRM outlook plugin

**Comment by mattlorimer** [comment]
it not a suitecrm plugin, it an outlook plugin, you need to unzip and run the .exe

**Comment by Narola123** [comment]
How to display sandbox in SuitCRM email Module.

**Comment by Narola123** [comment]
On 06-04-2016 01:12 PM, Matt Lorimer wrote:
>
> it not a suitecrm plugin, it an outlook plugin, you need to unzip and 
> run the .exe
>
How to display sandbox in SuitCRM Email Module.?
